routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'home');

Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::get('home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::resource('role','RoleController');
    Route::prefix('profile')->group(function () {
        Route::GET('/', 'ProfileController@index')->name('profile.index');
        Route::GET('edit', 'ProfileController@edit')->name('profile.edit');
        Route::PATCH('update', 'ProfileController@update')->name('profile.update');
    });
    Route::resource('authority', 'AuthorityController');
    Route::resource('dentist',   'DentistController');
    Route::resource('member',    'MemberController');
    Route::resource('medicines', 'MedicineController');
    Route::resource('equipment', 'EquipmentController');
    Route::resource('treatments', 'TreatmentController');
    Route::resource('appointments', 'AppointmentsController');

    Route::PATCH('success/appointment', 'AppointmentsController@success');

    Route::GET('treatments/confirm/create', 'TreatmentController@confirm')->name('treatments.confirm');
    Route::POST('treatments/treatments', 'TreatmentController@save')->name('treatments.save');
    Route::GET('treatments/confirm/change', 'TreatmentController@confirm_change')->name('treatments.confirm_change');
    Route::PATCH('treatments/treatments/{treatment}', 'TreatmentController@change')->name('treatments.change');

    Route::resource('payments', 'PaymentController');
    Route::get('payments/print/{payment}', 'PaymentController@print')->name('payments.print');

    Route::resource('type_medicines', 'UnitMedicinesController');
    Route::resource('type_equipment', 'UnitEquipmentController');

    Route::resource('reimbursement_medicines', 'ReimbursementMedicinesController');
    Route::resource('reimbursement_equipment', 'ReimbursementEquipmentController');

    Route::PATCH('takeback/reimbursement_medicines', 'ReimbursementMedicinesController@takeback')->name('reimbursement_medicines.takeback');
    Route::PATCH('takeback/reimbursement_equipment', 'ReimbursementEquipmentController@takeback')->name('reimbursement_equipment.takeback');

    Route::GET('/json-medicines/{medicine}', 'ApiController@medicines');
    Route::GET('/json-equipment/{equipment}', 'ApiController@equipment');

    Route::get('stock_medicines',    'StockMedicineController@index')->name('stock_medicines.index');
    Route::post('stock_medicines',   'StockMedicineController@store')->name('stock_medicines.store');
    Route::delete('stock_medicines', 'StockMedicineController@delete')->name('stock_medicines.delete');

    Route::get('stock_equipment',    'StockEquipmentController@index')->name('stock_equipment.index');
    Route::post('stock_equipment',   'StockEquipmentController@store')->name('stock_equipment.store');
    Route::delete('stock_equipment', 'StockEquipmentController@delete')->name('stock_equipment.delete');
});

resources/views/405.blade.php
@extends('layouts.app')
@section('title', 'หน้าหลัก')
@section('content')
<div class="content justify-content-center align-items-center mt-5">
    <div class="flex-fill"></div>
        <div class="text-center mb-3">
        <h1 class="error-title">405</h1>
        <h5 class="font f-24">  คุณไม่สิทธิ์ในการใช้งานหน้านี้  </h5>
        <br>
        <div class="row">
            <div class="col-xl-4 offset-xl-4 col-md-8 offset-md-2">
                <div class="row font">
                    <div class="col-sm-6">
                        <a href="{{ URL::previous() }}" class="btn btn-light btn-block mt-3 mt-sm-0 f-22"><i class="icon-arrow-left8 mr-2"></i> ย้อนกลับ </a>
                    </div>
                    <div class="col-sm-6">
                        <a href="{{ route('home') }}" class="btn btn-primary btn-block f-22"><i class="icon-home4 mr-2"></i>  หน้าหลัก </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('title', 'Home | หน้าหลัก')
@section('content')
@include('layouts.template.header', ['icon'=> 'icon-home2', 'name' => 'หน้าหลัก'])
<div class="content">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h6 class="card-title font"> ผู้ใช้งาน และ ผู้รับริการ </h6>
                </div>
                <div class="card-body px-2">
                    <div class="row">
                        <div class="col-sm-4 col-6">
                            <div class="d-flex align-items-center justify-content-center mb-2">
                                <a href="{{ route('authority.index') }}"
                                    class="btn bg-transparent border-warning-400 text-warning-400 rounded-round border-2 btn-icon mr-3">
                                    <i class="icon-users"></i>
                                </a>
                                <div>
                                    <div class="font-weight-semibold font f-20"> เจ้าหน้าที่ </div>
                                    <span class="text-muted f-16"> {{ users_count("authority") }} </span>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4 col-6">
                            <div class="d-flex align-items-center justify-content-center mb-2">
                                <a href="{{ route('dentist.index') }}"
                                    class="btn bg-transparent border-teal text-teal rounded-round border-2 btn-icon mr-3">
                                    <i class="fa fa-user-md f-18"></i>
                                </a>
                                <div>
                                    <div class="font-weight-semibold font f-20"> หมอ </div>
                                    <span class="text-muted f-16"> {{ users_count("dentist") }} </span>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4 col-6">
                            <div class="d-flex align-items-center justify-content-center mb-2">
                                <a href="{{ route('member.index') }}"
                                    class="btn bg-transparent border-indigo-400 text-indigo-400 rounded-round border-2 btn-icon mr-3">
                                    <i class="icon-users4"></i>
                                </a>
                                <div>
                                    <div class="font-weight-semibold font f-20"> ผู้รับบริการ </div>
                                    <span class="text-muted f-16"> {{ users_count("member") }} </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h6 class="card-title font"> รายงานการรักษา ประจำปี {{ Carbon::now()->year + 543 }}</h6>
                </div>
                <div class="card-body px-2">
                    <div class="row">
                        <div class="width_chart">
                            <canvas id="ChartTreatment" height="100"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
{!! Html::style('template/plugins/chart/Chart.min.css') !!}
@endpush

@push('scripts')
{!! Html::script('template/plugins/chart/Chart.min.js') !!}
{!! Html::script('template/plugins/chart/config.js') !!}
<script>
var treatment      = document.getElementById('ChartTreatment').getContext('2d');
var ChartTreatment = new Chart(treatment, {
    type: 'bar',
    data: {
        labels: short,
        datasets: [{
            data: [@foreach(treatment_month() as $rs) {{ $rs }}, @endforeach],
            backgroundColor: color,
            borderColor: border,
            borderWidth: 1
        }]
    },
    options: {
        legend: {
            display: false
        },
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true,
                    stepSize: 1,
                    max : {{ max(treatment_month()) + 2 }}
                }
            }]
        }
    }
});
</script>
@endpush