routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'home');

Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::get('home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::resource('role','RoleController');
    Route::prefix('profile')->group(function () {
        Route::GET('/', 'ProfileController@index')->name('profile.index');
        Route::GET('edit', 'ProfileController@edit')->name('profile.edit');
        Route::PATCH('update', 'ProfileController@update')->name('profile.update');
    });
    Route::resource('authority', 'AuthorityController');
    Route::resource('dentist',   'DentistController');
    Route::resource('member',    'MemberController');
    Route::resource('medicines', 'MedicineController');
    Route::resource('equipment', 'EquipmentController');
    Route::resource('treatments', 'TreatmentController');
    Route::resource('appointments', 'AppointmentsController');

    Route::PATCH('success/appointment', 'AppointmentsController@success');

    Route::GET('treatments/confirm/create', 'TreatmentController@confirm')->name('treatments.confirm');
    Route::POST('treatments/treatments', 'TreatmentController@save')->name('treatments.save');
    Route::GET('treatments/confirm/change', 'TreatmentController@confirm_change')->name('treatments.confirm_change');
    Route::PATCH('treatments/treatments/{treatment}', 'TreatmentController@change')->name('treatments.change');

    Route::resource('payments', 'PaymentController');
    Route::get('payments/print/{payment}', 'PaymentController@print')->name('payments.print');

    Route::resource('type_medicines', 'UnitMedicinesController');
    Route::resource('type_equipment', 'UnitEquipmentController');

    Route::resource('reimbursement_medicines', 'ReimbursementMedicinesController');
    Route::resource('reimbursement_equipment', 'ReimbursementEquipmentController');

    Route::PATCH('takeback/reimbursement_medicines', 'ReimbursementMedicinesController@takeback')->name('reimbursement_medicines.takeback');
    Route::PATCH('takeback/reimbursement_equipment', 'ReimbursementEquipmentController@takeback')->name('reimbursement_equipment.takeback');

    Route::GET('/json-medicines/{medicine}', 'ApiController@medicines');
    Route::GET('/json-equipment/{equipment}', 'ApiController@equipment');

    Route::get('stock_medicines',    'StockMedicineController@index')->name('stock_medicines.index');
    Route::post('stock_medicines',   'StockMedicineController@store')->name('stock_medicines.store');
    Route::delete('stock_medicines', 'StockMedicineController@delete')->name('stock_medicines.delete');

    Route::get('stock_equipment',    'StockEquipmentController@index')->name('stock_equipment.index');
    Route::post('stock_equipment',   'StockEquipmentController@store')->name('stock_equipment.store');
    Route::delete('stock_equipment', 'StockEquipmentController@delete')->name('stock_equipment.delete');
});

app/Models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    public function scopeGetDesc($query)
    {
        return $query->orderBy('created_at', 'DESC')->get();
    }

    public function treatment()
    {
        return $this->belongsTo(Treatment::class);
    }

    public function authority()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Payment;
use Auth;
use PDF;

class PaymentController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:payments-list');
    }

    public function index()
    {
        $payments = Payment::GetDesc();
        return view("payment.index")->with(['payments' => $payments]);
    }

    public function show(Payment $payment)
    {
        return view('payment.show')->with(['payment' => $payment]);
    }

    public function update(Payment $payment)
    {
        $payment->status  = "success";
        $payment->user_id = Auth::user()->id;
        $payment->save();
        return redirect()->route("payments.index")->with('success','Successfully');
    }

    public function print(Payment $payment)
    {
        return PDF::loadView('payment.print', compact('payment'))->download('payment.pdf');
    }
}

resources/views/payment/index.blade.php
@extends('layouts.app')
@section('title', 'Payment | การชำระเงิน')
@section('content')
@include('layouts.template.header',['icon'=> 'icon-cash  f-18', 'name' => 'การชำระเงิน'])
<div class="content">
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title font"> ข้อมูลการชำระเงิน </h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped datatable-treatments">
                    <thead>
                        <tr class="bg-slate-600 text-center">
                            <th class="text-center">ลำดับ</th>
                            <th>หัวข้อการรักษา</th>
                            <th>หมอ</th>
                            <th>ผู้รับบริการ</th>
                            <th>วันเวลาที่ตรวจรักษา</th>
                            <th>รวมค่าใช้จ่าย</th>
                            <th>สถานะการจ่ายเงิน</th>
                            <th>วันเวลาที่ชำระเงิน</th>
                            <th>เจ้าหน้าที่อนุมัติ</th>
                            <th>กระทำ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($payments as $k => $rs)
                        <tr>
                            <td class="text-center"> {{ ++$k }} </td>
                            <td class="text-left">
                                <a data-fancybox data-type="iframe" data-src="{{ route('payments.show', $rs->id) }}" href="javascript:;">
                                    {{ $rs->treatment->title }}
                                </a>
                            </td>
                            <td class="text-center"> {{ $rs->treatment->dentist->name  }} </td>
                            <td class="text-center"> {{ $rs->treatment->member->name   }} </td>
                            <td class="text-center"> {{ date_thai($rs->created_at, TRUE) }} </td>
                            <td class="text-center"> {{ number_format($rs->treatment->total, 0) }} </td>
                            <td class="text-center">
                                @switch($rs->status)
                                    @case('proceed')
                                    <span class="badge badge-flat border-warning text-warning-600 font f-16"> กำลังดำเนินการ </span>
                                    @break
                                    @case('success')
                                    <span class="badge badge-flat border-success text-success-600 font f-16"> จ่ายแล้ว </span>
                                    @break
                                @endswitch
                            </td>
                            <td class="text-center">
                                @if($rs->status == "success")
                                {{ date_thai($rs->updated_at, TRUE) }}
                                @endif
                            </td>
                            <td class="text-center">
                                @if($rs->status == "success")
                                    {{ $rs->authority->name }}
                                @endif
                            </td>
                            <td class="center">
                                @switch($rs->status)
                                    @case("proceed")
                                    <button class="btn btn-outline-success font f-18 border-2 btn-approve" data-id="{{ $rs->id }}"> <i class="icon-point-right mr-2"></i> อนุมัติ </button>
                                    {{ Form::open(['method' => 'PATCH', 'route' => ['payments.update', $rs->id], 'id'=>'approve-'.$rs->id])}} {{ Form::close() }}
                                    @break
                                    @case("success")
                                    <a target="_blank" class="btn btn-outline-info font f-18 border-2" href="{{ route('payments.print', $rs->id) }}"> <i class="fa fa-print"></i> </a>
                                    @break
                                @endswitch
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
</div>
@endsection

@if (session('approve'))
    <script>
        swal({ title: 'Success!', text: 'ทำการชำระเงินเรียบร้อยแล้ว', type: 'success'});
    </script>
@endif

@push('scripts')
    <script>
    $('.btn-approve').on('click',function(){
        const id = $(this).data('id');
        swal({
            title: 'Are you sure?',
            text: "ต้องการที่จะยืนยัน การชำระเงิน นี้ใช่หรือไม่ !!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'ยืนยัน',
            cancelButtonText: 'ยกเลิก',
            confirmButtonClass: 'btn btn-success',
            cancelButtonClass: 'btn btn-danger',
            buttonsStyling: false
        }).then(function (result) {
            if (result.value) {
                $( "#approve-"+id ).submit();
            }
        });
    });
    </script>
@endpush

resources/views/payment/print.blade.php
<!DOCTYPE html>
<html>
  <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
      <title> ใบเสร็จรับเงิน </title>
      <style>
        body { font-family: "THSarabunNew" }

        .absolute {
            position: absolute;
            text-align: right;
            vertical-align: middle;
        }

        table.separate {
            border-collapse: separate;
            width: 100%;
        }

        table.collapse {
            border-collapse: collapse;
            border: 1px solid black;
        }

        table.collapse td {
            padding-bottom : 10px;
        }

        table.collapse th {
            border: 1px solid black
        }

        .full-width {
            width: 100%;
        }

        th {
            text-align: center;
            vertical-align: middle;
        }

        td,th {
            vertical-align: middle;
        }

        .bold {
            font-weight : bold;
        }

        .border {
            border-left: 1px solid black;
        }

        .center {
            text-align: center;
        }

        .right {
            text-align: right;
        }

        .left {
            text-align: left;
        }

        .m_left {
            margin-left : 10px
        }

        .m_right {
            margin-right : 10px
        }

        .f_right {
            float : right;
        }

        .f_left {
            float : left;
        }
      </style>
  </head>
  <body marginwidth="0" marginheight="0">

    <h1>ใบเสร็จรับเงิน (Receipt) <span class="f_right"> คลินิกทันตกรรมอารมณ์ดี </span> </h1>
    <h3>
      <span class="m_right"> เล่มที่ {{ sprintf( "%00d", $payment->id ) }}  </span> <span class="f_right">  โทรศัพท์ 053-299558 เบอร์โทร 093-2781154 </span>
    </h3>
    <h3>
      <span class="m_right"> เลขที่ {{ sprintf( "%04d", $payment->id ) }}  </span> <span class="f_right">  ถนน โชตนา อ.แม่ริม จ.เชียงใหม่ 50180 </span>
    </h3>
    <hr>
    <br>

    <table class="separate">
      <tbody>
        <tr>
          <td width="15%"> <span style="font-weight:bold;font-size:20px"> หมอ </span> </td>
          <td> <span style="font-size:20px;"> {{ $payment->treatment->dentist->name }} </span> </td>
          <td width="20%"> <span style="font-weight:bold;font-size:20px"> วัน/เวลา ตรวจรักษา </span> </td>
          <td> <span style="font-size:20px;"> {{ date_thai($payment->created_at, TRUE) }} </span> </td>
        </tr>
        <tr>
          <td width="15%"> <span style="font-weight:bold;font-size:20px"> ผู้รับบริการ </span> </td>
          <td> <span style="font-size:20px;"> {{ $payment->treatment->member->name }} </span> </td>
          <td width="20%"> <span style="font-weight:bold;font-size:20px"> วัน/เวลา ชำระเงิน  </span> </td>
          <td> <span style="font-size:20px;"> {{ date_thai($payment->updated_at, TRUE) }} </span> </td>
        </tr>
      </tbody>
    </table>

    <br>
    <hr>


    <table class="separate">
      <tbody>
        <tr>
          <td class="center"> <span style="font-size:20px;"> {{ $payment->treatment->title }}  </span> </td>
        </tr>
      </tbody>
    </table>

    <br>


    <h3 style="margin-top:-10px;"> รายการรักษา </h3>
    <table class="collapse full-width">
      <thead>
        <tr>
          <th width="80%"> รายการ </th>
          <th width="20%"> ราคา  </th>
        </tr>
      </thead>
      <tbody>
        @foreach ($payment->treatment->details_treatment as $item)
        <tr>
            <td class="border">
                <span class="m_left"> {{ $item->name }} </span>
            </td>
            <td class="border center">
                <span class="m_left"> {{ number_format($item->price) }} </span>
            </td>
        </tr>
        @endforeach
      </tbody>
    </table>

    @isset($payment->treatment->details_medicine[0])
    <h3> รายการยา </h3>
    <table class="collapse full-width">
      <thead>
        <tr>
          <th width="80%"> รายการ </th>
          <th width="20%"> ราคา  </th>
        </tr>
      </thead>
      <tbody>
        @foreach ($payment->treatment->details_medicine as $item)
        <tr>
            <td class="border">
                <span class="m_left"> {{ $item->name }} </span>
            </td>
            <td class="border center">
                <span class="m_left"> {{ number_format($item->price) }} </span>
            </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    @endisset

    <br>
    <p class="f_right bold" style="font-size: 20px"> รวมเงินทั้งสิ้น  {{ number_format($payment->treatment->total, 2,'.', ',') }} บาท ({{ Numberthai($payment->treatment->total) }}) </p>
    <br>
    <br>
    <br>
    <hr>
    <hr>

  </body>
</html>

resources/views/payment/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <link rel="icon" href="/image/favicon.png" type="image/x-icon" />
    {!! Html::style('template/plugins/formvalidation/dist/css/formValidation.min.css') !!}
    {!! Html::style("template/assets/css/icons/icomoon/styles.css") !!}
    {!! Html::style("template/assets/css/icons/fontawesome/styles.min.css") !!}
    {!! Html::style("template/assets/css/bootstrap.min.css")!!}
    {!! Html::style("template/assets/css/bootstrap_limitless.min.css") !!}
    {!! Html::style("template/assets/css/layout.min.css")!!}
    {!! Html::style("template/assets/css/components.min.css") !!}
    {!! Html::style("template/assets/css/colors.min.css") !!}
    {!! Html::style('template/plugins/flatpickr/flatpickr.min.css') !!}
    {!! Html::style('template/plugins/clockpicker/clockpicker.css') !!}
    {!! Html::style('template/plugins/fancybox-master/dist/jquery.fancybox.min.css') !!} 
    {!! Html::style("css/font.css") !!}
    {!! Html::style("css/style.css") !!}
    {!! Html::script("template/assets/js/main/jquery.min.js") !!}
    {!! Html::script("template/assets/js/main/bootstrap.bundle.min.js") !!}
    {!! Html::script("template/assets/js/plugins/loaders/blockui.min.js") !!}
    {!! Html::script("template/assets/js/plugins/ui/ripple.min.js") !!}
    {!! Html::script("template/assets/js/plugins/notifications/sweet_alert.min.js")!!}
    {!! Html::script("template/assets/js/plugins/ui/perfect_scrollbar.min.js")!!}
    {!! Html::script("template/assets/js/plugins/forms/styling/uniform.min.js")!!}
    {!! Html::script("template/assets/js/plugins/forms/selects/select2.min.js")!!}
    {!! Html::script("template/assets/js/plugins/forms/selects/bootstrap_multiselect.js")!!}
    {!! Html::script("template/assets/js/plugins/tables/datatables/datatables.min.js")!!}
    {!! Html::script('template/plugins/formvalidation/dist/js/FormValidation.min.js')    !!}
    {!! Html::script('template/plugins/formvalidation/dist/js/plugins/Bootstrap.min.js') !!}
    {!! Html::script('template/plugins/flatpickr/flatpickr.js') !!}
    {!! Html::script('template/plugins/flatpickr/th.js') !!}
    {!! Html::script('template/plugins/clockpicker/clockpicker.js') !!}
    {!! Html::script('template/plugins/fancybox-master/dist/jquery.fancybox.min.js') !!} 
    {!! Html::script("template/assets/js/app.js") !!}
</head>
<body>
    <div class="page-content">
        <div class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-body border-top-info">
                        <h6 class="mb-3 font-weight-semibold font f-22">
                            รายละเอียดการชำระเงิน
                        </h6>
                        <div class="card">
                            <div class="card-body text-center">
                                <h6 class="font-weight-semibold mb-0 font f-22"> <strong> หัวข้อการักษา </strong> </h6>
                                <span class="d-block text-muted font f-20"> {{ $payment->treatment->title }} </span>
                            </div>
                        </div>
                        <div class="card card-body bg-light mb-0">
                            {{-- Dentist --}}
                            <dl class="row mb-0">
                                <dt class="col col-sm-1 font text-right">
                                    <strong> หมอ </strong>
                                </dt>
                                <dd class="col-sm-10">
                                    {{ $payment->treatment->dentist->name }}
                                </dd>
                            </dl>
                            {{-- Member --}}
                            <dl class="row mb-0">
                                <dt class="col col-sm-1 font text-right">
                                    <strong> ผู้รับบริการ </strong>
                                </dt>
                                <dd class="col-sm-3">
                                    {{ $payment->treatment->member->name }}
                                </dd>
                            </dl>
                            <hr>
                            {{-- Fees --}}
                            <dl class="row mb-0">
                                <dt class="col col-sm-1 font text-right">
                                    <strong> รายการที่รักษา </strong>
                                </dt>
                                <dd class="col-sm-10 font">
                                    <div class="row">
                                        @foreach ($payment->treatment->details_treatment as $item)
                                        <div class="col-md-5">
                                            {{ $item->name }}
                                        </div>
                                        <div class="col-md-1 text-center">
                                            <b class="mr-3"> ราคา </b>
                                        </div>
                                        <div class="col-md-1 text-left">
                                            {{ number_format($item->price) }}
                                        </div>
                                        <div class="col-md-1 text-center">
                                            <b class="ml-3"> บาท </b>
                                        </div>
                                        @endforeach
                                    </div>
                                </dd>
                            </dl>
                            @isset($payment->treatment->details_medicine[0])
                            <hr>
                            {{-- Medicines --}}
                            <dl class="row mb-0">
                                <dt class="col col-sm-1 font text-right">
                                    <strong> รายการยาที่เลือก </strong>
                                </dt>
                                <dd class="col-sm-10 font">
                                    <div class="row">
                                        @foreach ($payment->treatment->details_medicine as $item)
                                        <div class="col-md-5">
                                            {{ $item->name }}
                                        </div>
                                        <div class="col-md-1 text-center">
                                            <b class="mr-3"> ราคา </b>
                                        </div>
                                        <div class="col-md-1 text-left">
                                            {{ number_format($item->price) }}
                                        </div>
                                        <div class="col-md-1 text-center">
                                            <b class="ml-3"> บาท </b>
                                        </div>
                                        @endforeach
                                    </div>
                                </dd>
                            </dl>
                            @endisset
                            <hr>
                            {{-- Total --}}
                            <dl class="row mb-0">
                                <dt class="col col-sm-1 font text-center">
                                    <strong> รวมทั้งสิ้น </strong>
                                </dt>
                                <dd class="col-sm-3">
                                    {{ number_format($payment->treatment->total) }}
                                    <b class="ml-3 font"> บาท </b>
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>