routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'home');

Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::get('home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::resource('role','RoleController');
    Route::prefix('profile')->group(function () {
        Route::GET('/', 'ProfileController@index')->name('profile.index');
        Route::GET('edit', 'ProfileController@edit')->name('profile.edit');
        Route::PATCH('update', 'ProfileController@update')->name('profile.update');
    });
    Route::resource('authority', 'AuthorityController');
    Route::resource('dentist',   'DentistController');
    Route::resource('member',    'MemberController');
    Route::resource('medicines', 'MedicineController');
    Route::resource('equipment', 'EquipmentController');
    Route::resource('treatments', 'TreatmentController');
    Route::resource('appointments', 'AppointmentsController');

    Route::PATCH('success/appointment', 'AppointmentsController@success');

    Route::GET('treatments/confirm/create', 'TreatmentController@confirm')->name('treatments.confirm');
    Route::POST('treatments/treatments', 'TreatmentController@save')->name('treatments.save');
    Route::GET('treatments/confirm/change', 'TreatmentController@confirm_change')->name('treatments.confirm_change');
    Route::PATCH('treatments/treatments/{treatment}', 'TreatmentController@change')->name('treatments.change');

    Route::resource('payments', 'PaymentController');
    Route::get('payments/print/{payment}', 'PaymentController@print')->name('payments.print');

    Route::resource('type_medicines', 'UnitMedicinesController');
    Route::resource('type_equipment', 'UnitEquipmentController');

    Route::resource('reimbursement_medicines', 'ReimbursementMedicinesController');
    Route::resource('reimbursement_equipment', 'ReimbursementEquipmentController');

    Route::PATCH('takeback/reimbursement_medicines', 'ReimbursementMedicinesController@takeback')->name('reimbursement_medicines.takeback');
    Route::PATCH('takeback/reimbursement_equipment', 'ReimbursementEquipmentController@takeback')->name('reimbursement_equipment.takeback');

    Route::GET('/json-medicines/{medicine}', 'ApiController@medicines');
    Route::GET('/json-equipment/{equipment}', 'ApiController@equipment');

    Route::get('stock_medicines',    'StockMedicineController@index')->name('stock_medicines.index');
    Route::post('stock_medicines',   'StockMedicineController@store')->name('stock_medicines.store');
    Route::delete('stock_medicines', 'StockMedicineController@delete')->name('stock_medicines.delete');

    Route::get('stock_equipment',    'StockEquipmentController@index')->name('stock_equipment.index');
    Route::post('stock_equipment',   'StockEquipmentController@store')->name('stock_equipment.store');
    Route::delete('stock_equipment', 'StockEquipmentController@delete')->name('stock_equipment.delete');
});

app/Models/Medicine.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Medicine extends Model
{
    protected $guarded = [];

    public function scopeGetDesc($query)
    {
        return $query->orderBy('created_at', 'DESC')->get();
    }

    public function medicine()
    {
        return $this->hasOne(Reimbursement::class);
    }
}

app/Models/Reimbursement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Reimbursement extends Model
{
    protected $guarded = [];

    public function medicine()
    {
        return $this->belongsTo(Medicine::class);
    }

    public function equipment()
    {
        return $this->belongsTo(Equipment::class);
    }
}

app/Http/Controllers/MedicineController.php
<?php

namespace App\Http\Controllers;

use App\Models\Medicine;
use App\Models\Unit;
use Illuminate\Http\Request;

class MedicineController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:medicines-list');
        $this->middleware('permission:medicines-create', ['only' => ['create','store']]);
        $this->middleware('permission:medicines-edit'  , ['only' => ['edit','update']]);
        $this->middleware('permission:medicines-delete', ['only' => ['destroy']]);
    }

    public function index()
    {
        $medicines = Medicine::get();
        return view('medicines.index')->with(['medicines' => $medicines]);
    }

    public function create()
    {
        return view('medicines.create')->with(['type' => Unit::where('type', 'medicine')->pluck('name', 'name')]);
    }

    public function store(Request $request)
    {
        $rules    = ['code' => 'required|unique:medicines', 'name' => 'required|unique:medicines'];
        $messages = ['code.unique' => 'มีรหัสยานี้อยุ่ในระบบแล้ว', 'name.unique' => 'มีชื่อยานี้อยู่ในระบบแล้ว'];
        $request->validate($rules,$messages);
        Medicine::create($request->all());
        return redirect()->route('medicines.index')->with('success','Successfully');

    }

    public function show(Medicine $medicine)
    {
        return view('medicines.show')->with(['medicine' => $medicine]);
    }

    public function edit(Medicine $medicine)
    {
        return view('medicines.edit')->with(['medicine' => $medicine])->with(['type' => Unit::where('type', 'medicine')->pluck('name', 'name')]);
    }

    public function update(Request $request, Medicine $medicine)
    {
        $rules    = ['code' => 'required|unique:medicines,code,'.$medicine->id, 'name' => 'required|unique:medicines,name,'.$medicine->id];
        $messages = ['code.unique' => 'มีรหัสยานี้อยุ่ในระบบแล้ว', 'name.unique' => 'มีชื่อยานี้อยู่ในระบบแล้ว'];
        $request->validate($rules,$messages);
        Medicine::updateOrCreate(['id'=>$medicine->id],$request->all());
        return redirect()->route('medicines.index')->with('update','Successfully');
    }

    public function destroy(Medicine $medicine)
    {
        Medicine::destroy($medicine->id);
        return redirect()->route('medicines.index')->with('delete','Successfully');
    }
}

resources/views/reimbursement/medicines/create.blade.php
@extends('layouts.app')
@section('title', 'เพิ่มการเบิกคืนยา')
@section('content')
@include('layouts.template.header', ['icon'=>'icon-aid-kit', 'name' => 'เพิ่มการเบิกคืนยา'])
<div class="content">
    {{ Form::open(['route'=>'reimbursement_medicines.store', 'id' => 'FormValidation']) }}
    @include('layouts.pattern.errors', ['errors' => $errors])
    <div class="card">
        <div class="card-body">
            <fieldset class="mb-3">
                <legend class="text-uppercase font-weight-bold font">
                    รายละเอียดการเบิกคืนยา
                </legend>
                <div class="form-group row">
                    {{ Form::label('medicine_id', 'ชื่อยา', ['class'=>'col-form-label col-lg-2 font']) }}
                    <div class="col-lg-10">
                        {{ Form::select('medicine_id', $medicines ,  NULL, ['class' => 'form-control select-search', 'placeholder'=>'-- เลือกชื่อยา --'] ) }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ Form::label('code', 'รหัสยา', ['class'=>'col-form-label col-lg-2 font']) }}
                    <div class="col-lg-10">
                        {{ Form::text('code', null, ['class' => 'form-control', 'readonly'] ) }}
                    </div>
                </div>
                <div class="form-group row form-group-feedback form-group-feedback-right">
                    {{ Form::label('disburse', 'จำนวนเบิกจ่าย', ['class'=>'col-form-label col-lg-2 font']) }}
                    <div class="col-lg-10">
                        {{ Form::number('disburse', null, ['class' => 'form-control phone'] ) }}
                        <div class="form-control-feedback form-control-feedback-lg mr-2">
                            <span class="unit"></span>
                        </div>
                        <span class="form-text text-muted balance"> คงเหลือ  <span id="amount">  </span> <span class="unit"></span> </span>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="text-center">
                <button type="submit" class="btn btn-primary font"> บันทึก <i class="icon-paperplane ml-2"></i></button>
            </div>
        </div>
    </div>
    {{ Form::close() }}
</div>
@endsection
@push('scripts')
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $('.balance').hide()

    $('#medicine_id').on('change', function(e){
        var medicine_id = e.target.value;
        if(medicine_id) {
            $('#disburse').prop("disabled", false);
            $.ajax({
                type: "GET",
                url: "/json-medicines/"+medicine_id,
                success: function(rs){
                    $('#medicine_id').val(rs.id)
                    $('#code').val(rs.code)
                    $('.unit').text(rs.type)
                    $('#amount').text(rs.amount)
                    $('.balance').show()
                }
            });
        } else {
            $('.balance').hide()
            $('#code').val("")
            $('#disburse').val("")
            $('.unit').text("")
            $('.amount').text("")
            $('#disburse').prop("disabled", true);
        }
    });

    document.addEventListener('DOMContentLoaded', function(e) {
        const form = document.getElementById('FormValidation');
        FormValidation.formValidation(form, {
            fields: {
                medicine_id: {
                    validators: {
                        notEmpty: {
                            message: 'กรุณาเลือกชื่อยา'
                        }
                    }
                },
                disburse: {
                    validators: {
                        notEmpty: {
                            message: 'กรุณากรอกจำนวนเบิกจ่าย'
                        },
                        numeric: {
                            message: 'The value is not a number',
                            thousandsSeparator: '',
                            decimalSeparator: '.'
                        }
                    }
                },
            },
            plugins: {
                trigger: new FormValidation.plugins.Trigger(),
                bootstrap: new FormValidation.plugins.Bootstrap(),
                submitButton: new FormValidation.plugins.SubmitButton(),
                defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
            },
        });
    });
</script>
@endpush

resources/views/reimbursement/medicines/edit.blade.php
@extends('layouts.app') 
@section('title', 'แก้ไขการเบิกคืนยา') 
@section('content')
@include('layouts.template.header', ['icon'=>'icon-aid-kit', 'name' => 'แก้ไขการเบิกคืนยา'])
<div class="content">
    {{ Form::model($reimbursement_medicine, ['method'=>'PATCH', 'route'=> ['reimbursement_medicines.update', $reimbursement_medicine->id], 'id' => 'FormValidation'])}}
    @include('layouts.pattern.errors', ['errors' => $errors])
    <div class="card">
        <div class="card-body">
            <fieldset class="mb-3">
                <legend class="text-uppercase font-weight-bold font">
                    รายละเอียดการเบิกคืนยา
                </legend>
                <div class="form-group row">
                    {{ Form::label('medicine_id', 'ชื่อยา', ['class'=>'col-form-label col-lg-2 font']) }}
                    <div class="col-lg-10">
                        {{ Form::hidden('medicine_id', $reimbursement_medicine->medicine_id) }}
                        {{ Form::text('name', $reimbursement_medicine->medicine->name , ['class' => 'form-control', 'readonly'] ) }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ Form::label('code', 'รหัสยา', ['class'=>'col-form-label col-lg-2 font']) }}
                    <div class="col-lg-10">
                        {{ Form::text('code', $reimbursement_medicine->medicine->code , ['class' => 'form-control', 'readonly'] ) }}
                    </div>
                </div>
                <div class="form-group row form-group-feedback form-group-feedback-right">
                    {{ Form::label('disburse', 'จำนวนเบิกจ่าย', ['class'=>'col-form-label col-lg-2 font']) }}
                    <div class="col-lg-10">
                        {{ Form::number('disburse', null, ['class' => 'form-control phone'] ) }}
                        <div class="form-control-feedback form-control-feedback-lg mr-2">
                            <span class="unit"> {{ $reimbursement_medicine->medicine->type }} </span>
                        </div>
                        <span class="form-text text-muted balance"> คงเหลือ  <span id="amount"> {{ $reimbursement_medicine->medicine->amount + $reimbursement_medicine->disburse }}  </span> <span class="unit"> {{ $reimbursement_medicine->medicine->type }} </span> </span>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="text-center">
                <button type="submit" class="btn btn-primary font"> บันทึก <i class="icon-paperplane ml-2"></i></button>
            </div>
        </div>
    </div>
    {{ Form::close() }}
</div>
@endsection
@push('scripts')
    <script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    document.addEventListener('DOMContentLoaded', function(e) {
        const form = document.getElementById('FormValidation');
        FormValidation.formValidation(form, {
            fields: {
                disburse: {
                    validators: {
                        notEmpty: {
                            message: 'กรุณากรอกจำนวนเบิกจ่าย'
                        },
                        numeric: {
                            message: 'The value is not a number',
                            thousandsSeparator: '',
                            decimalSeparator: '.'
                        }
                    }
                },
            },
            plugins: {
                trigger: new FormValidation.plugins.Trigger(),
                bootstrap: new FormValidation.plugins.Bootstrap(),
                submitButton: new FormValidation.plugins.SubmitButton(),
                defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
            },
        });
    });
    </script>
@endpush

resources/views/reimbursement/medicines/index.blade.php
@extends('layouts.app')
@section('title', 'Reimbursement Medicines | การเบิกคืนยา')
@section('content')
@include('layouts.template.header',['icon'=> 'icon-aid-kit', 'name' => 'การเบิกคืนยา'])
<div class="content">
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title font"> ข้อมูลการเบิกคืนยา </h5>
            @can('reimbursement_medicines-create')
            <a href="{{ route('reimbursement_medicines.create') }}" class="btn alpha-blue text-blue-800 border-blue-600 font" style="font-size:18px">
                <i class="icon-folder-plus3 mr-2"></i> เพิ่มการเบิกคืนยา
            </a>
            @endcan
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped datatable-reimbursement">
                    <thead>
                        <tr class="bg-slate-600 text-center">
                            <th class="text-center">ลำดับ</th>
                            <th> รหัส </th>
                            <th> ชื่อ </th>
                            <th> จำนวนเบิกจ่าย </th>
                            <th> จำนวนส่งคืน </th>
                            <th> จำนวนคงเหลือ </th>
                            <th> สถานะ </th>
                            <th> วันที่เบิกจ่าย </th>
                            <th> วันที่ส่งคืน </th>
                            <th> กระทำ </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($medicines as $k => $rs)
                        <tr>
                            <td class="text-center"> {{ ++$k }}</td>
                            <td class="text-center">{{ $rs->medicine->code }}</td>
                            <td>{{ $rs->medicine->name }}</td>
                            <td class="text-center">{{ $rs->disburse }}</td>
                            <td class="text-center">{{ $rs->takeback }}</td>
                            <td class="text-center">{{ $rs->balance  }}</td>
                            <td class="text-center">
                                @switch($rs->status)
                                    @case('disburse')
                                    <span class="badge badge-flat border-warning text-warning-600 font f-20"> เบิกจ่าย </span>
                                    @break
                                    @case('takeback')
                                    <span class="badge badge-flat border-success text-success-600 font f-20"> ส่งคืน </span>
                                    @break
                                @endswitch
                            </td>
                            <td class="text-center">{{ date_thai($rs->created_at) }}</td>
                            <td class="text-center">{{ $rs->datetime ? date_thai($rs->datetime): NULL }}</td>
                            <td class="center">
                                <div class="list-icons">
                                    @switch($rs->status)
                                        @case('disburse')
                                            <button class="btn btn-success" 
                                            data-id="{{ $rs->id }}" 
                                            data-toggle="modal" 
                                            data-target="#modal_form" 
                                            data-popup="tooltip" 
                                            title="ส่งคืน" 
                                            data-placement="bottom"
                                            >
                                            <i class="icon-folder-download2"></i>
                                            </button>
                                            <a href="{{ route('reimbursement_medicines.show', $rs->id) }}" data-popup="tooltip" title="รายละเอียด" data-placement="bottom" class="btn btn-primary" title="ดูข้อมูล">
                                                <i class="icon-eye"></i>
                                            </a>
                                            @can('reimbursement_medicines-edit')
                                            <a class="btn btn-warning btn-edit" href="{{ route('reimbursement_medicines.edit',$rs->id) }}" data-popup="tooltip" title="แก้ไข" data-placement="bottom">
                                                <i class="icon-pencil7"></i>
                                            </a>
                                            @endcan
                                            @can('reimbursement_medicines-delete')
                                            <button class="btn btn-danger  btn-del" data-id="{{ $rs->id }}" data-popup="tooltip" title="ลบ" data-placement="bottom">
                                                <i class="icon-trash"></i>
                                            </button>
                                            {{ Form::open(['method' => 'DELETE', 'route' => ['reimbursement_medicines.destroy', $rs->id], 'id'=>'delete-'.$rs->id])}} {{ Form::close() }}
                                            @endcan
                                        @break
                                        @case('takeback')
                                            <a href="{{ route('reimbursement_medicines.show', $rs->id) }}" data-popup="tooltip" title="รายละเอียด" data-placement="bottom" class="btn btn-primary" title="ดูข้อมูล">
                                                <i class="icon-eye"></i>
                                            </a>
                                            @can('reimbursement_medicines-delete')
                                                <button class="btn btn-danger  btn-del" data-id="{{ $rs->id }}" data-popup="tooltip" title="ลบ" data-placement="bottom">
                                                    <i class="icon-trash"></i>
                                                </button>
                                                {{ Form::open(['method' => 'DELETE', 'route' => ['reimbursement_medicines.destroy', $rs->id], 'id'=>'delete-'.$rs->id])}} {{ Form::close() }}
                                            @endcan
                                        @break
                                    @endswitch
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
</div>
<!-- Reimbursement form modal -->
<div id="modal_form" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> จำนวนส่งคืน </h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            {{ Form::open(['route'=>'reimbursement_medicines.takeback', 'method' => 'PATCH']) }}
                <div class="modal-body">
                    @if($errors->any())
                    <div class="alert alert-danger text-center">
                        @foreach ($errors->all() as $error)
                            <p class="font fs-20">{!! $error !!}</p>
                        @endforeach
                    </div>
                    @endif
                    {{ Form::hidden('id', null, ['id'=>'id']) }}
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                {{ Form::number('takeback', 0, ['class' => 'form-control', 'autofocus', 'required', 'id'=>'takeback'] ) }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link font" data-dismiss="modal"> ปิด </button>
                    <button type="submit" class="btn bg-primary font"> บันทึก </button>
                </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
<!-- /Reimbursement form modal -->
@endsection

@push('scripts')
  <script>
    @if(count($errors) > 0)
        $('#modal_form').modal('show');
    @endif

    $('#modal_form').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        $(this).find('.modal-body #id').val(id)
        $(this).find('.modal-body #takeback').val(0)
    });
  </script>  
@endpush

resources/views/reimbursement/medicines/show.blade.php
@extends('layouts.app') 
@section('title', 'ข้อมูลประเภทยา') 
@section('content')
@include('layouts.template.header', ['icon'=>'icon-aid-kit', 'name' => 'ข้อมูลประเภทยา'])
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-body border-top-info">
                <h6 class="mb-3 font-weight-semibold font f-22">
                    รายละเอียดการเบิกคืนยา
                    @switch($reimbursement_medicine->status)
                        @case('disburse')
                            <span class="float-right badge badge-flat border-warning text-warning-600 font f-20"> เบิกจ่าย </span>
                        @break
                        @case('takeback')
                            <span class="float-right badge badge-flat border-success text-success-600 font f-20"> ส่งคืน </span>
                        @break
                    @endswitch
                </h6>
                <div class="card">
                    <div class="card-body text-center">
                        <h6 class="font-weight-semibold mb-0 font f-22"> <strong> รหัสยา </strong> </h6>
                        <span class="d-block text-muted font f-20"> {{ $reimbursement_medicine->medicine->code }} </span>
                    </div>
                </div>
                <div class="card card-body bg-light mb-0">
                    <dl class="row justify-content-md-center mb-0">
                        <dt class="col col-sm-3 font text-right">
                                <strong> ชื่อยา </strong>
                            </dt>
                        <dd class="col-sm-3">
                            {{ $reimbursement_medicine->medicine->name }}
                        </dd>
                    </dl>
                    <dl class="row justify-content-md-center mb-0">
                        <dt class="col col-sm-3 font text-right">
                                <strong> จำนวนเบิกจ่าย </strong>
                            </dt>
                        <dd class="col-sm-3">
                            {{ $reimbursement_medicine->disburse }}
                        </dd>
                    </dl>
                    <dl class="row justify-content-md-center mb-0">
                        <dt class="col col-sm-3 font text-right">
                                <strong> จำนวนรับคืน </strong>
                            </dt>
                        <dd class="col-sm-3">
                            {{ $reimbursement_medicine->takeback }}
                        </dd>
                    </dl>
                    <dl class="row justify-content-md-center mb-0">
                        <dt class="col col-sm-3 font text-right">
                                <strong> จำนวนคงเหลือ </strong>
                            </dt>
                        <dd class="col-sm-3">
                            {{ $reimbursement_medicine->balance }}
                        </dd>
                    </dl>
                    <dl class="row justify-content-md-center mb-0">
                        <dt class="col col-sm-3 font text-right">
                            <strong> วันที่เบิกจ่าย </strong>
                        </dt>
                        <dd class="col-sm-3">
                            {{ date_thai($reimbursement_medicine->created_at) }}
                        </dd>
                    </dl>
                    <dl class="row justify-content-md-center mb-0">
                        <dt class="col col-sm-3 font text-right">
                            <strong> วันที่รับคืน </strong>
                        </dt>
                        <dd class="col-sm-3">
                            {{ $reimbursement_medicine->datetime ? date_thai($reimbursement_medicine->datetime): NULL }}
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection