routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'home');

Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::get('home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::resource('role','RoleController');
    Route::prefix('profile')->group(function () {
        Route::GET('/', 'ProfileController@index')->name('profile.index');
        Route::GET('edit', 'ProfileController@edit')->name('profile.edit');
        Route::PATCH('update', 'ProfileController@update')->name('profile.update');
    });
    Route::resource('authority', 'AuthorityController');
    Route::resource('dentist',   'DentistController');
    Route::resource('member',    'MemberController');
    Route::resource('medicines', 'MedicineController');
    Route::resource('equipment', 'EquipmentController');
    Route::resource('treatments', 'TreatmentController');
    Route::resource('appointments', 'AppointmentsController');

    Route::PATCH('success/appointment', 'AppointmentsController@success');

    Route::GET('treatments/confirm/create', 'TreatmentController@confirm')->name('treatments.confirm');
    Route::POST('treatments/treatments', 'TreatmentController@save')->name('treatments.save');
    Route::GET('treatments/confirm/change', 'TreatmentController@confirm_change')->name('treatments.confirm_change');
    Route::PATCH('treatments/treatments/{treatment}', 'TreatmentController@change')->name('treatments.change');

    Route::resource('payments', 'PaymentController');
    Route::get('payments/print/{payment}', 'PaymentController@print')->name('payments.print');

    Route::resource('type_medicines', 'UnitMedicinesController');
    Route::resource('type_equipment', 'UnitEquipmentController');

    Route::resource('reimbursement_medicines', 'ReimbursementMedicinesController');
    Route::resource('reimbursement_equipment', 'ReimbursementEquipmentController');

    Route::PATCH('takeback/reimbursement_medicines', 'ReimbursementMedicinesController@takeback')->name('reimbursement_medicines.takeback');
    Route::PATCH('takeback/reimbursement_equipment', 'ReimbursementEquipmentController@takeback')->name('reimbursement_equipment.takeback');

    Route::GET('/json-medicines/{medicine}', 'ApiController@medicines');
    Route::GET('/json-equipment/{equipment}', 'ApiController@equipment');

    Route::get('stock_medicines',    'StockMedicineController@index')->name('stock_medicines.index');
    Route::post('stock_medicines',   'StockMedicineController@store')->name('stock_medicines.store');
    Route::delete('stock_medicines', 'StockMedicineController@delete')->name('stock_medicines.delete');

    Route::get('stock_equipment',    'StockEquipmentController@index')->name('stock_equipment.index');
    Route::post('stock_equipment',   'StockEquipmentController@store')->name('stock_equipment.store');
    Route::delete('stock_equipment', 'StockEquipmentController@delete')->name('stock_equipment.delete');
});

app/Models/Unit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    protected $guarded = [];
}

resources/views/units/midicines/create.blade.php
@extends('layouts.app')
@section('title', 'เพิ่มประเภทยา')
@section('content')
@include('layouts.template.header', ['icon'=>'icon-aid-kit', 'name' => 'เพิ่มประเภทยา'])
<div class="content">
    {{ Form::open(['route'=>'type_medicines.store', 'id' => 'FormValidation']) }}
    @include('layouts.pattern.errors', ['errors' => $errors])
    <div class="card">
        <div class="card-body">
            <fieldset class="mb-3">
                <legend class="text-uppercase font-weight-bold font">
                    รายละเอียดประเภทยา
                </legend>
                <div class="form-group row">
                    {{ Form::label('name', 'ชื่อประเภทยา', ['class'=>'col-form-label col-lg-2 font']) }}
                    {{ Form::hidden('type', 'medicine') }}
                    <div class="col-lg-10">
                        {{ Form::text('name', null, ['class' => 'form-control'] ) }}
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="text-center">
                <button type="submit" class="btn btn-primary font"> บันทึก <i class="icon-paperplane ml-2"></i></button>
            </div>
        </div>
    </div>
    {{ Form::close() }}
</div>
@endsection
@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function(e) {
        const form = document.getElementById('FormValidation');
        FormValidation.formValidation(form, {
            fields: {
                name: {
                    validators: {
                        notEmpty: {
                            message: 'กรุณากรอกชื่อประเภทยา'
                        }
                    }
                },
            },
            plugins: {
                trigger: new FormValidation.plugins.Trigger(),
                bootstrap: new FormValidation.plugins.Bootstrap(),
                submitButton: new FormValidation.plugins.SubmitButton(),
                defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
            },
        });
    });
</script>
@endpush

resources/views/units/midicines/edit.blade.php
@extends('layouts.app')
@section('title', 'แก้ไขประเภทยา')
@section('content')
@include('layouts.template.header', ['icon'=>'icon-aid-kit', 'name' => 'เพิ่มประเภทยา'])
<div class="content">
    {{ Form::model($medicines, ['method'=>'PATCH', 'route'=> ['type_medicines.update', $medicines->id], 'id' => 'FormValidation']) }}
    @include('layouts.pattern.errors', ['errors' => $errors])
    <div class="card">
        <div class="card-body">
            <fieldset class="mb-3">
                <legend class="text-uppercase font-weight-bold font">
                    รายละเอียดประเภทยา
                </legend>
                <div class="form-group row">
                    {{ Form::label('name', 'ชื่อประเภทยา', ['class'=>'col-form-label col-lg-2 font']) }}
                    <div class="col-lg-10">
                        {{ Form::text('name', null, ['class' => 'form-control'] ) }}
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="text-center">
                <button type="submit" class="btn btn-primary font"> บันทึก <i class="icon-paperplane ml-2"></i></button>
            </div>
        </div>
    </div>
    {{ Form::close() }}
</div>
@endsection
@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function(e) {
        const form = document.getElementById('FormValidation');
        FormValidation.formValidation(form, {
            fields: {
                name: {
                    validators: {
                        notEmpty: {
                            message: 'กรุณากรอกชื่อประเภทยา'
                        }
                    }
                },
            },
            plugins: {
                trigger: new FormValidation.plugins.Trigger(),
                bootstrap: new FormValidation.plugins.Bootstrap(),
                submitButton: new FormValidation.plugins.SubmitButton(),
                defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
            },
        });
    });
</script>
@endpush

resources/views/units/midicines/index.blade.php
@extends('layouts.app')
@section('title', 'Type Medicines | ประเภทยา')
@section('content')
@include('layouts.template.header',['icon'=> 'icon-aid-kit', 'name' => 'ประเภทยา'])
<div class="content">
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title font"> ข้อมูลประเภทยา </h5>
            @can('type_medicines-create')
            <a href="{{ route('type_medicines.create') }}" class="btn alpha-blue text-blue-800 border-blue-600 font" style="font-size:18px">
                <i class="icon-folder-plus3 mr-2"></i> เพิ่มประเภทยา
            </a>
            @endcan
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped datatable-type">
                    <thead>
                        <tr class="bg-slate-600 text-center">
                            <th class="text-center">ลำดับ</th>
                            <th>ชื่อ</th>
                            <th>กระทำ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($medicines as $k => $rs)
                        <tr>
                            <td class="text-center"> {{ ++$k }}      </td>
                            <td class="text-center"> {{ $rs->name }} </td>
                            <td class="center">
                                @include('layouts.pattern.action', ['name'=> 'type_medicines', 'id' => $rs->id])
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/units/midicines/show.blade.php
@extends('layouts.app')
@section('title', 'ข้อมูลประเภทยา')
@section('content')
@include('layouts.template.header', ['icon'=> 'icon-hammer-wrench', 'name' => 'ข้อมูลประเภทยา'])
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-body border-top-info">
                <h6 class="mb-3 font-weight-semibold font f-22">
                    รายละเอียดประเภทยา
                </h6>
                <div class="card">
                    <div class="card-body text-center">
                        <h6 class="font-weight-semibold mb-0 font f-22"> <strong> ประเภทยา </strong> </h6>
                        <span class="d-block text-muted font f-20"> {{ $medicines->name }} </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection